config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :stores, except: :create
  resources :tags,   only: [:show, :destroy, :create]
  root  'pages#home'
  post   'upload'       => 'stores#upload'
  get    'download/:id' => 'stores#download', as: :download
  get    '/contact'     =>  'pages#contact'
  get    '/about'       =>  'pages#about'
  get    '/help'        =>  'pages#help'
  get    '/signup'      =>  'users#new'
  get    '/login'       =>  'sessions#new'
  post   '/login'       =>  'sessions#create'
  get    '/logout'      =>  'sessions#destroy'
  get    '/search'      =>   'search_engines#index'
  post   '/search'      =>   'search_engines#search'

end

app/models/store.rb
# == Schema Information
#
# Table name: stores
#
#  id         :integer          not null, primary key
#  public     :boolean
#  filename   :string(255)
#  location   :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

require 'fileutils'
class Store < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags
  @@home = "#{Rails.root}/public/data"

  def self.empty_dir(local_dir)   # local directory is like "/1/home"
    local_dir = File.join(@@home, local_dir)
    if File.directory? local_dir
      FileUtils.rm_rf(Dir.glob("#{local_dir}/*"))
    end
  end

  def self.make_dir(local_dir)
    if !File.directory? local_dir
      FileUtils::mkdir_p local_dir
    end
  end

  def self.make_local_dir(dir)
    local_dir = File.join(@@home, dir)
    make_dir(local_dir)
  end

  def self.move(filename, pre_dest, next_dest)
    local_dir = File.join(@@home, "#{next_dest}")
    make_dir(local_dir)
    filename = File.join(@@home, "#{pre_dest}/#{filename}")
    FileUtils.mv(filename, local_dir)
  end

  def self.save(upload)
    filename = upload['file'].original_filename.downcase
    destination = upload['location']
    local_dir = File.join(@@home, "#{destination}")
    make_dir(local_dir)
    path = File.join(local_dir, filename)
    File.open(path, "wb") do |f|
      f.write(upload['file'].read)
    end
  end

  def self.remove(filename, location)
    file = File.join(@@home, "#{location}/#{filename}")
    File.delete(file)
  end

  def self.rename(filename1, filename2, location)
    local_dir = File.join(@@home, "#{location}")
    FileUtils.mv("#{local_dir}/#{filename1}", "#{local_dir}/#{filename2}")
  end

  def self.filePath(filename, location)
    local_dir = File.join(@@home, "#{location}/#{filename}")
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  before_filter :authenticate 
  before_filter :correct_owner_user,  :only => [:edit, :update, :destroy]

  def index
    @stores = Store.all
    @store = Store.new
  end

  def show
    @store = Store.where(id: params[:id]).first
    @tag = Tag.new
  end

  def edit
    @store = Store.where(id: params[:id]).first
  end

  def update
    @store = Store.where(id: params[:id]).first
    @tag = Tag.new
    if @store.filename != params[:store][:filename]
      Store.rename(@store.filename, params[:store][:filename], @store.location)
    end
    if @store.location != params[:store][:location]
      Store.move(params[:store][:filename], @store.location, params[:store][:location])
    end
    @store.update_attributes(store_params)
    render 'show'
  end

  def destroy
    @store = Store.where(id: params[:id]).first
    Store.remove(@store.filename, @store.location)
    @store.destroy
    redirect_to stores_path
  end

  def upload
    Store.save(params[:store])
    @store = Store.new(public: params[:store][:public],
                       filename: params[:store][:file].original_filename.downcase,
                       location: params[:store][:location],
                       user_id: params[:store][:user_id])
    @store.save
    redirect_to stores_path
  end

  def download
    @store = Store.where(id: params[:id]).first
    if @store.public || !@store.public && correct_user?(@store.user)
      redirect_to "/data#{@store.location}/#{@store.filename}"
    else
      redirect_to root_path, :flash => {:error => "not autherised for this action"}
    end
  end

  private
  def store_params
    params.require(:store).permit(:public, :filename, :location)
  end

  def correct_owner_user
    @user = Store.find(params[:id]).user
    redirect_to(root_path) unless correct_user?(@user)
  end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/edit.html.erb
<h1> Edit Store/file Information </h1>

<%= form_for(@store) do |f| %>
  <div class="field">
    <%= f.label :filename %> <br/>
    <%= f.text_field :filename %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="field">
    <%= f.label :location %> <br/>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :private %>
    <%= f.radio_button :public, false%>
    <%= f.label :public %>
    <%= f.radio_button :public, true %>
  </div>

  <div class="actions">
    <%= f.submit "Update!!" %>
  </div>
<% end %>

app/views/stores/index.html.erb
<h1>All Files</h1>


<ul>
  <% @stores.each do |store| %>
    <% if (store.public) %>
      <li> <%= link_to "#{store.filename}", store %> </li>
    <%end%>
  <% end %>
</ul>

<% if @stores.size == 0 %>
  <%= "no files available" %>
<% end %>
<div class="form">
  <h1> Upload your file </h1>
  <%= form_for(@store, :url => upload_path) do |f|%>
    <div class="field">
      <%= f.label :file %> 
      <%= f.file_field :file %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>
    <div class="field">
      <%= f.label :location %>
      <%= f.text_field :location , :value => "/#{current_user.id}/"%>
    <div class="field">
      <%= f.label :private %>
      <%= f.radio_button :public, false %>
      <%= f.label :public %>
      <%= f.radio_button :public, true %>
    </div>
    <div class="actions">
    <%= f.submit "Upload" %>
    </div>
  <% end %>
</div>

app/views/stores/show.html.erb
<h1> File/Store Information </h1>
<div class="info">
  <h2> Filename: <%= @store.filename %> </h2>
  <h2> Location: <%= @store.location %> </h2>
  <h3> Public  : <%= @store.public %> </h2>
</div>

<div class="links">
  <tr>
    <td>
      <%= link_to "edit", edit_store_path(@store) %>
    </td>
    <td>
      <%= link_to "delete",store_path(@store), method: :delete %>
    </td>
    <td>
      <%= link_to "download", download_path(@store) %>
    </td>
  </tr>
</div>

<div class="tags">
  <h5> tags for this file </h5>
  <% @store.tags.each do |tag| %>
    <ul>
      <%= link_to tag.name, tag_path(tag), :file => @store %>
      <%= link_to "remove tag", tag_path(tag, :file => @store.id), method: :delete %>
    </ul>
  <% end %>
</div>

<div class="form">
  <h5> add a tag to this file </h5>
  <%= form_for(@tag) do |f| %>
    <div class="fields">
      <%= f.text_field :name %>
      <%= f.hidden_field :file, :value => @store.id %>
    </div>

    <div class="actions">
      <%= f.submit "add tag!!" %>
    </div>
  <% end %>
</div>