config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :stores, except: :create
  resources :tags,   only: [:show, :destroy, :create]
  root  'pages#home'
  post   'upload'       => 'stores#upload'
  get    'download/:id' => 'stores#download', as: :download
  get    '/contact'     =>  'pages#contact'
  get    '/about'       =>  'pages#about'
  get    '/help'        =>  'pages#help'
  get    '/signup'      =>  'users#new'
  get    '/login'       =>  'sessions#new'
  post   '/login'       =>  'sessions#create'
  get    '/logout'      =>  'sessions#destroy'
  get    '/search'      =>   'search_engines#index'
  post   '/search'      =>   'search_engines#search'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  salt               :string(255)
#  encrypted_password :string(255)
#

class User < ActiveRecord::Base

  has_many :stores
  attr_accessor  :password 
 
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
  validates :name,     :presence     => true,
                       :length       => { :maximum => 50 }
  validates :email,    :presence     => true,
                       :format       => {:with => email_regex },
                       :uniqueness   => { :case_sensitive => false }
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
  before_save :encrypt_password

  def User.authenticate(email, submitted_password)
     user = find_by_email(email)
     (user && user.has_password?(submitted_password)) ? user : nil
  end

  def User.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def has_password?(submitted_password)
     encrypted_password == encrypt(submitted_password)
  end  
  private

  def encrypt_password
     self.salt = make_salt if new_record?
     self.encrypted_password = encrypt(self.password)
  end


  def encrypt(string)
     secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate , :only => [:index, :edit, :update]
  before_filter :correct_user,  :only => [:edit, :update]

  def index
    @users = User.all
    @title = "All users"
  end

  def new
    @user = User.new
    @title="Sign up"
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      local_dir = "/#{@user.id}"
      Store.make_local_dir(local_dir)
      flash[:success] = "Welcome to the sample App"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id]) 
    @title = "Edit User"
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user, :flash => { :success => "Profile updated" }
    else
      @title = "Edit User"
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless correct_user?(@user)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<%= render 'users/shared/error_messages' %>
  <div class="field">
    <%= f.label :name %> <br/>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %> <br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %> <br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %> <br />
    <%= f.password_field :password_confirmation %>
  </div>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>

  <%= render 'fields', :f => f  %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>

<% end %>

app/views/users/index.html.erb
<h1>All users</h1>


<ul class="users">
  <% @users.each do |user| %>
    <li> <%= link_to "#{user.name}", user %> </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'fields' , :f => f %>

  <div class="actions">
    <%= f.submit "Sign up"%>
  </div>

<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= @user.name %>
      </h1>
      <br/>
      <% @user.stores.each do |store| %>
        <h5><%= link_to store.filename, store_path(store) %></h5>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), user_path(@user) %>
    </td>
  </tr>
</table>