config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :stores, except: :create
  resources :tags,   only: [:show, :destroy, :create]
  root  'pages#home'
  post   'upload'       => 'stores#upload'
  get    'download/:id' => 'stores#download', as: :download
  get    '/contact'     =>  'pages#contact'
  get    '/about'       =>  'pages#about'
  get    '/help'        =>  'pages#help'
  get    '/signup'      =>  'users#new'
  get    '/login'       =>  'sessions#new'
  post   '/login'       =>  'sessions#create'
  get    '/logout'      =>  'sessions#destroy'
  get    '/search'      =>   'search_engines#index'
  post   '/search'      =>   'search_engines#search'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class= "round">
     <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "News", 'http://news.railstutorial.org' %></li>
        <li><%= link_to "Rails Tutorial", 'http://railstutorial.org' %></li>
     </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path  %>
  <nav class= "round">
     <ul>
       <li><%= link_to "Home", root_path %></li>
       <% if logged_in? %>
         <li><%= link_to "Profile", current_user %></li>
         <li><%= link_to "Upload", stores_path %></li>
         <li><%= link_to "Search", search_path %></li>
         <li><%= link_to "Users", users_path %></li>
         <li><%= link_to "Settings", edit_user_path(current_user) %></li>
       <% end %>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path  %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
     </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class = "round">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>